# Generated by Django 5.1.4 on 2024-12-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hudsons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcRevisao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('tipo', models.CharField(choices=[('revisao_ortografica', 'Revisão Ortográfica'), ('revisao_critica', 'Revisão Crítica')], max_length=50)),
                ('quant_pag', models.IntegerField()),
                ('custo_pag', models.FloatField()),
                ('diagramacao', models.BooleanField(default='False')),
                ('custo_diagramacao', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('data_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='InfoUsuario',
        ),
    ]
