# Generated by Django 5.1.4 on 2024-12-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hudsons', '0002_calcrevisao_usuario_delete_infousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcrevisao',
            name='tipo',
            field=models.CharField(choices=[('tcc', 'TCC'), ('dissertacao', 'Dissertação'), ('tese', 'Tese')], max_length=50),
        ),
    ]
