# Generated by Django 5.1.4 on 2024-12-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hudsons', '0004_calcrevisao_data_alter_calcrevisao_diagramacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcrevisao',
            name='custo_diagramacao',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
