# Generated by Django 5.1.4 on 2024-12-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hudsons', '0006_alter_calcrevisao_diagramacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcrevisao',
            name='diagramacao',
            field=models.BooleanField(),
        ),
    ]
