# Generated by Django 5.1.4 on 2024-12-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hudsons', '0007_alter_calcrevisao_diagramacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcrevisao',
            name='custo',
            field=models.FloatField(default=0.0),
        ),
    ]
