# Generated by Django 5.1.4 on 2024-12-21 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hudsons', '0009_calcrevisao_usuario_alter_calcrevisao_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
